#include <stdio.h>

#define global
#define bool	    int
#define false	    0
#define true	    1
#define unless(x)   if(!(x))
#define until(x)    while(!(x))

#define ABGD1	330	/* ops for makeabgd in general case */
#define ABGD2	122	/* ops for makeabgd for TM	    */

extern "C" void strcat(char*, char*);

static void printheading(), test_genprog_1(), test_genprog_2(), test_tmprog();
static int countops(char[]);
static void fail(char*);


global int main()
  { printheading();
    test_genprog_1();
    test_genprog_2();
    test_tmprog();
    return 0;
  }

static void printheading()
  { printf(".\\\" tbl source generated by .../coco/conformal/testit\n");
    printf(".\\\" Pipe into: | tbl | troff -me | psdit | pstops '0(1.0in,0.7in)' | lp -L\n");
    putchar('\n');
  }

static void test_genprog_1()
  { int i, n, nw;
    printf(".ip \"Table 1\"\n");
    printf(".TS\n");
    printf("allbox, tab(:);\n");
    printf("c s s s s s s s s s s s s\n");
    printf("c c c c c c c c c c c c c\n");
    printf("n n n n n n n n n n n n n.\n");
    printf("Total operation count for Algorithm 1\n_\n");
    printf("\\fIN\\fP : \\fIK\\fP = 8 "); for (nw=16; nw <= 16384; nw <<= 1) printf(": %d", nw); printf("\n_\n");
    for (n = 32; n <= 16384; n <<= 1)
      { printf("%d", n);
	for (nw = 8; nw <= n; nw <<= 1)
	  { char cmd[257];
	    sprintf(cmd, "genprog T %d 0 %d", n, nw);
	    int ncm = countops(cmd);
	    printf(" : %d", 3*ncm + ABGD2);
	  }
	putchar('\n');
      }
    printf(".TE\n\n");
  }

static void test_genprog_2()
  { int i, n, nw;
    printf(".ip \"Table 2\"\n");
    printf(".TS\n");
    printf("allbox, tab(:);\n");
    printf("c s s s s s s s s s s s s\n");
    printf("c c c c c c c c c c c c c\n");
    printf("n n n n n n n n n n n n n.\n");
    printf("Operation count per projected point for Algorithm 1\n_\n");
    printf("\\fIN\\fP : \\fIK\\fP = 8 "); for (nw=16; nw <= 16384; nw <<= 1) printf(": %d", nw); printf("\n_\n");
    for (n = 32; n <= 16384; n <<= 1)
      { printf("%d", n);
	for (nw = 8; nw <= n; nw <<= 1)
	  { char cmd[257];
	    sprintf(cmd, "genprog T %d 0 %d", n, nw);
	    int ncm = countops(cmd);
	    printf(" : %.3f", (double) (3*ncm + ABGD2) / (double) nw);
	  }
	putchar('\n');
      }
    printf(".TE\n\n");
  }

static void test_tmprog()
  { int n;
    printf(".ip \"Table 3\"\n");
    printf(".TS\n");
    printf("allbox, tab(:);\n");
    printf("c s s s\nc c c c\nn n n n.\n");
    printf("Operation count for Algorithm 2\n_\n");
    printf("\\fIN\\fP : \\fIK\\fP : \\fIfpops\\fP : \\fIfpops/pt\\fP\n_\n");
    for (n = 32; n <= 16384; n <<= 1)
      { char cmd[257];
	sprintf(cmd, "tmprog %d", n);
	int ncm = countops(cmd);
	printf("%d : %d : %d : %.3f\n", n, n, 3*ncm + 2*ABGD2, (double) (3*ncm + 2*ABGD2) / (double) (2*n));
      }
    printf(".TE\n\n");
  }

static int countops(char cmd[])
  { strcat(cmd, " 2>&1 >/dev/null");      /* append this to cmd */
    FILE *pfi = popen(cmd, "r");
    if (pfi == NULL) fail("popen failed");
    bool ok = false; int ncm;
    until (ok || feof(pfi))
      { char line[257];
	line[0] = '\0'; /* in case fgets fails */
	fgets(line, 256, pfi);
	if (sscanf(line, "*** %d complex multiplies", &ncm) == 1) ok = true;
      }
    int code = pclose(pfi);
    unless (ok) fail("sscanf error");
    unless (code == 0) fail("pclose failed");
    return ncm;
  }

static void fail(char *msg)
  { fprintf(stderr, "testit: %s\n", msg);
    exit(1);
  }

