/* Make table of coeffs for "trig" method of polar-to-OS conversion
   A.J. Fisher	 July 1995 */

#include <stdio.h>
#include <hdr.h>

#include "trighdr.h"

#define AL	9.9833027342682179e-01	    /* coeffs for Bomford's formula for m(phi) */
#define A2	2.5056370533281126e-03
#define A4	2.6202371293300089e-06
#define A6	3.3816589942819785e-09

#define C1	1.0050365011826925e+00	    /* 1.0 + 3.0*C3			    */
#define C3	1.6788337275641298e-03	    /* 0.25 * (ESQUARED / (1.0 - ESQUARED)) */

static double linterm[NDERIVS];
static double avec[NDERIVS][NHARMS+3], bvec[NDERIVS][NHARMS+3]; /* padding reqd for convolution */


global main()
  { makederivs();
    printderivs();
    exit(0);
  }

#define aval(n)	  (((n) > 0) ? (n)*av[n] : -(n)*av[-(n)])	/* n * a[n] */
#define bval(n)	  (((n) > 0) ? (n)*bv[n] : +(n)*bv[-(n)])	/* n * b[n] */

static makederivs()
  { int j, k;
    double *av = avec[0], *bv = bvec[0];
    for (j=0; j < NHARMS; j++) av[j] = bv[j] = 0.0;
    av[2] = -A2; av[4] = A4; av[6] = -A6;
    linterm[0] = AL;
    for (j=1; j < NDERIVS; j++)
      { double *av1 = avec[j], *bv1 = bvec[j];
	double fac = 1.0 / (double) (2*j);
	/* add zero padding for convolution */
	for (k=0; k < 3; k++) av[NHARMS+k] = bv[NHARMS+k] = 0.0;
	/* convolve */
	for (k=0; k < NHARMS; k++)
	  { av1[k] = -fac * (C1 * (bval(k-1) + bval(k+1)) + C3 * (bval(k-3) + bval(k+3)));
	    bv1[k] = fac * (C1 * (aval(k-1) + aval(k+1)) + C3 * (aval(k-3) + aval(k+3)));
	  }
	bv1[0] *= 0.5;
	bv1[1] += linterm[j-1] * C1;
	bv1[3] += linterm[j-1] * C3;
	linterm[j] = 0.0;
	av = av1; bv = bv1;
      }
  }

static printderivs()
  { int i, j;
    printf("/* File generated by mktable */\n\n");
    printf("#define global\n\n");
    printf("global double linterm = %23.16e;\n\n", linterm[0]);
    printf("global double cvec[%d][%d] = {\n", NDERIVS, NHARMS/2);
    for (i=0; i < NDERIVS; i++)
      { double *vec = (i&1) ? &bvec[i][1] : &avec[i][0];
	for (j=0; j < NHARMS; j += 2)
	  { if (j%8 == 0) printf((j == 0) ? "  { " : "    ");
	    printf("%23.16e, ", vec[j]);
	    if (j%8 == 6) putchar('\n');
	  }
	printf("  },\n");
      }
    printf("};\n");
  }

